apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snak-ingress
spec:
  rules:
    - host: app.snak.dev
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: snak-app-service
                port:
                  number: 8080
