apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: snak-app-dev

bases:
  - ../../base

namespace: development

commonLabels:
  environment: dev

replicas:
  - name: snak-app-deployment
    count: 1

patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: snak-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: app.snak.dev
