apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: snak-app-dev

bases:
  - ../../base

namespace: development

commonLabels:
  environment: dev

replicas:
  - name: snak-app-deployment
    count: 1
