apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: snak-app-dev

bases:
  - ../../base

namespace: development

commonLabels:
  environment: dev

replicas:
  - name: snak-app-deployment
    count: 1

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: snak-app-deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: APP_STORE
            value: "redis"
          - name: APP_REDIS_URL
            value: "redis://snak-app-dragonfly.development.svc.cluster.local:6379"

images:
  - name: andreqko/snak-app
    newTag: dev
