apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: snak-app-prod

namespace: production

bases:
  - ../../base

commonLabels:
  environment: prod

replicas:
  - name: snak-app-deployment
    count: 3
  - name: snak-app-dragonfly
    count: 2

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: snak-app-deployment
      namespace: production
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

resources:
  - hpa.yaml

images:
  - name: andreqko/snak-app
    newTag: latest
