apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: snak-app-prod

namespace: production

bases:
  - ../../base

commonLabels:
  environment: prod

replicas:
  - name: snak-app-deployment
    count: 3

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: snak-app-deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
  - target:
      group: dragonflydb.io
      version: v1alpha1
      kind: Dragonfly
      name: snak-app-dragonfly
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: snak-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: app.snak

resources:
  - hpa.yaml

images:
  - name: andreqko/snak-app
    newTag: latest
