apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: snak-app-prod

namespace: production

bases:
  - ../../base

commonLabels:
  environment: prod

replicas:
  - name: snak-app-deployment
    count: 3

configMapGenerator:
  - name: snak-config
    behavior: merge
    literals:
      - APP_REDIS_URL=redis://snak-app-dragonfly.production.svc.cluster.local:6379

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: snak-app-deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

  - target:
      group: dragonflydb.io
      version: v1alpha1
      kind: Dragonfly
      name: snak-app-dragonfly
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

patchesStrategicMerge:
  - ingress-patch.yaml

resources:
  - hpa.yaml

images:
  - name: andreqko/snak-app
    newTag: latest
