apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: snak-app

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - dragonfly.yaml

configMapGenerator:
  - name: snak-config
    literals:
      - APP_STORE=redis
      - APP_REDIS_URL=redis://snak-app-dragonfly.svc.cluster.local:6379

commonLabels:
  app.kubernetes.io/name: snak-app
  app.kubernetes.io/managed-by: flux
