apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: snak-app

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - dragonfly.yaml

commonLabels:
  app.kubernetes.io/name: snak-app
  app.kubernetes.io/managed-by: flux
